### ISSUE TITLE
大佬，我想要一个文件

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [YuukiPS/Launcher-Android#1]
我看到您的run.sh 脚本中有一个 ./metadata-patcher.exe patch xxx，大佬能不能把这个文件给我一份，圈钱死🐴

**Comment by ElaXan** [comment]
what???

bruhh thats for patch this APK to AnimeGame for who have Android No Root can use this patch.

**Comment by ErrorCodesForLzx** [comment]
@ElaXan  But I want to compile from “ original apk ” to "Patched apk" by my self ，Can you give my step，Thank very much！！！！
CHS： 但是我想自己编译从原apk到打包apk，但是不知道步骤，您能不能给我一个步骤，万分感谢！！

**Comment by ElaXan** [comment]
@ErrorCodesForLzx 
i dont know where metadata-patcher.exe is.
maybe thats private (cant share to public)

if you want patch by yourself. you can...
but use metadata that already patched by someone or Yuki
and replace original metadata to patched metadata in assets/bin/Data/Managed/Metadata/
dont forget to sign the APK

thats all i can say.

**Comment by ErrorCodesForLzx** [comment]
@ElaXan  Thank at all

**Comment by ErrorCodesForLzx** [comment]
@ElaXan 
大佬您好，我遇到了一个问题，就是我通过别人修补过的APK里面的metadata.bat移动到了我修补的APK文件里面进入大门会显示”12-4301 账号验证错误“，我认为好像是连接到了官服，我又到您的提供的网站上尝试找答案，但是我无法进入您提供的discord(提示 空白频道)，请问我能不能借用一点您宝贵的时间给我说一说如何修改metadata文件呢，绝不圈钱|！！！！！
🐧：514389135 如果可以的话万分感谢！！！！！！！！！

**Comment by ErrorCodesForLzx** [comment]
@ElaXan 
Hello, boss, I have a problem with metadata in APK that I have patched through others When bat moves to the APK file I patched, it will display "12-4301 account verification error". I think it seems that it is connected to the official service, and I try to find the answer on the website you provided, but I cannot access the discord (prompt blank channel) you provided. Can I borrow some of your precious time to tell me how to modify the metadata file, and never save money |!!!!!
🐧： 514389135 Thank you if you can!!!!!!!!!

**Comment by ElaXan** [comment]
@ErrorCodesForLzx 

3.1 using UA Patch not Metadata.

For website i will check it as soon as possible.
Here for [Discord](https://discord.gg/yuukips-964119462188040202)

**Comment by ErrorCodesForLzx** [comment]
@ElaXan  
your discord say "邀请无效"，how to fix it ？

**Comment by hht805656153** [comment]
这个项目3.1失效了。要么你去找方块君付费定制，要么等3.2版本更新后等他GitHub放出3.1。目前我看到网上的3.1版本的Android客户端都是方块君定制的，不能自定义，看包内的Xposed模块签名就知道了，都是一样的签名，二改的话，签名不可能一样。

**Comment by moux23333** [comment]
3.2通用包已经有了
3.1/3.2电脑版修补的是Native/UserAssembly.dll
手机版修补的是lib/libil2cpp.so

ENG:
3.2 patched apk(with custom IP feature)already have
3.1/3.2 PC should patch Native/UserAssembly
Android APK should patch lib/libil2cpp.so
@ElaXan 577xfk already released 3.1 proxy module,you can check his repo to try to fix your module and i already tell you what files you need to patch lol
good luck

**Comment by ElaXan** [comment]
> 3.2通用包已经有了 3.1/3.2电脑版修补的是Native/UserAssembly.dll 手机版修补的是lib/libil2cpp.so @ElaXan 577xfk已经在他的仓库里发布了3.1的代理模块，你可以参考他的东西来修复你的模块，并且我已经告诉了你该修补哪些东西 祝你好运
> 
> ENG: 3.2 patched apk(with custom IP feature)already have 3.1/3.2 PC should patch Native/UserAssembly Android APK should patch lib/libil2cpp.so @ElaXan 577xfk already released 3.1 proxy module,you can check his repo to try to fix your module and i already tell you what files you need to patch lol good luck

Done with new patch, and have 2 option download
1. Custom Server and Localhost but cant play Official Server
2. Can Official Server but cant play Custom Server and Localhost

For number 2 using Chinese module but i add 1 more module to replace Chinese server to Yuuki Server.

You can check in [Discord Server Yuuki](https://discord.gg/yuukips)

**Comment by ElaXan** [comment]
@moux23333 source code?
Just edit it and compile

See my [fork](https://github.com/ElaXan/AnimeGameAPK)
