### ISSUE TITLE
"Failed to Extract il2cpp" 错误通常与 Unity 游戏的反编译有关。

### ISSUE THREAD

**Issue by GuguguBear** [YuukiPS/Launcher-Android#10]
在你的项目中，我没有看到与 Unity 或 il2cpp 直接相关的配置。

然而，这个错误可能与你的 NDK 配置有关，因为 il2cpp 是 Unity 用于将 C# 代码转换为 C++ 的工具，然后使用 NDK 进行编译。

你的项目中的 NDK 配置如下：

```
ndk {
    abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
}
```

这个配置指定了你的应用支持的 ABI（应用二进制接口）。

如果某些设备的 ABI 不在这个列表中，那么它们可能无法正确加载你的应用的 native 库，从而导致 "Failed to Extract il2cpp" 错误。

另外，你的项目依赖于一些外部库，如 'de.robv.android.xposed:api:82' 和 'com.github.kyuubiran:EzXHelper:0.9.2'。

如果这些库包含 native 代码，并且没有为所有 ABI 提供预编译的二进制文件，那么在某些设备上可能会出现问题。

建议你检查以下几点：

1. 确保你的 NDK 版本与你的 Unity 版本兼容。
2. 检查你的外部库是否为所有 ABI 提供了预编译的二进制文件。
3. 如果可能，尝试在出现问题的设备上运行你的应用，并查看 logcat 输出，以获取更多关于错误的信息。

希望这些信息对你有所帮助。

**Comment by Xuoos** [comment]
你就没发现unityhook就没有被使用吗，它只是被打包进了安装包内，仅此而已，出现此错误你应该检查游戏本体
