### ISSUE TITLE
I solve the il2cpp error

### ISSUE THREAD

**Issue by katiksiz-mal** [YuukiPS/Launcher-Android#3]
When we delete the "Unity" and "il2cpp" folder in the game's data folder and enter the game, the game opens without an error.

**Comment by ElaXan** [comment]
> When we delete the "Unity" and "il2cpp" folder in the game's data folder and enter the game, the game opens without an error.

Can you provide more details about this?

**Comment by TititGede** [comment]
> > When we delete the "Unity" and "il2cpp" folder in the game's data folder and enter the game, the game opens without an error.
> 
> Can you provide more details about this?

![Screenshot_20221217-052653](https://user-images.githubusercontent.com/115709435/208199387-fa706b57-e950-4c5e-95a2-5995e27c4d43.jpg)

**Comment by TititGede** [comment]
> > When we delete the "Unity" and "il2cpp" folder in the game's data folder and enter the game, the game opens without an error.
> 
> Can you provide more details about this?

Android/data/com.miHoYo.GenshinImpact/files
![Screenshot_20221217-053034~2](https://user-images.githubusercontent.com/115709435/208199598-e2b76156-6648-4ec6-8b29-0de7507dd807.jpg)

**Comment by ElaXan** [comment]
Bruh i know where the folder path is 💀

Nvm i will try that, if work will add to code
